url: https://y7kim.github.io
baseurl:

# Site settings
title: Blackmill
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
exclude:
- vendor/bundle
# Team names, titles and social links
people:
- name: Robert Card
  pic: robert_card_dj
  position: Founder, Producer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/blackmillmusic
  - title: facebook
    url: https://www.facebook.com/Blackmill-167224433307649
  - title: spotify
    url: https://open.spotify.com/artist/4kjWnaLfIRcLJ1Dy4Wr6tY
  - title: soundcloud
    url: https://soundcloud.com/blackmill
  - title: apple
    url: https://geo.itunes.apple.com/us/album/reach-for-glory/id423339211?mt=1&app=music
  - title: amazon
    url: https://music.amazon.com/artists/B004PW1SJ6/CATALOG?ref=dm_wcp_artist_link_pr_s
  - title: youtube
    url: https://www.youtube.com/user/BlackmillMusic
  - title: tumblr
    url: http://blackmill.tumblr.com/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
